<div id="titulo">Registro de Tipo de Producción</div>
<div class="col-md-6 col-md-offset-3">


	
	<form id="agregar">
	  
	  <div class="form-group">
	    <label for="Cedula">Tipo de Producción</label>
	    <input type="text" class="form-control" id="nombre_tipo" name="nombre_tipo" placeholder="Ejemplo: Panadero">
	   
	  </div>

	  <button type="button" id="guardar" class="btn btn-default">Guardar</button>
	  <button type="button" id="inicio"  class="btn btn-default">Inicio</button>
	</form>
</div>

</div>
		