
<input type="hidden" id="cant_regis" value="<?php echo count($this->lista) ?>"> 
<div class="col-md-12">


			<!--header-->	

            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">LISTADOS DE EMPRESAS PRODUCTORAS</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <input type="text" id="buscar" class="form-control" name="">
                    <a href="<?php echo BASE_URL ?>pdf/lista?id=<?php echo $this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
                    <a href="<?php echo BASE_URL ?>pdf/lista?id=<?php echo $this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>

                  </div>
                </div>
              </div>





              <!-- body-->

              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><em class="fa fa-cog"></em></th>
                        <th class="hidden-xs">Nro</th>
                        <th class="hidden-xs">CODIGO SICA</th>
                        <th class="hidden-xs">RIF</th>
                        <th>RAZON SOCIAL</th>
                        <th>TIPO DE PRODUCTOR</th>
                         <th>Cant</th> 
                        <th><em class="fa fa-cog"></em></th>

                    </tr> 
                  </thead>
                
                  
                <tbody>

<!--ciclo............................................................................................ -->
							<?php for ($i=0; $i < count($this->lista)  ; $i++):?>	
                          <tr id="fila<?php echo $i+1 ?>" class="">
                            <td align="center">
                              <a href="<?php echo BASE_URL ?>pdf/comprobante_registro?id=<?php echo $this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>
                                <a href="<?php echo BASE_URL ?>regis_emp/actualizar?id=<?php echo $this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                                <a href="<?php echo  BASE_URL.'lista/eliminar?id='.$this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                
                                 <a id="detalle<?php echo $i+1 ?>" data-id="detalle<?php echo $i+1 ?>" class="btn btn-default" ><span data-id="<?php echo $i+1 ?>" class="glyphicon   glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>

                                  <a  class="btn btn-default" ><span data-id="<?php echo $i+1 ?>" class="glyphicon   glyphicon glyphicon-eye-close" aria-hidden="true"></span></a>
                            
                            </td>

                            <td><?php echo '0000'.$this->lista[$i]['id_emp'] ?></td>
                            <td><?php echo $retVal = ($this->lista[$i]['codigo_sica']=="") ? 'NO POSEE' : $this->lista[$i]['codigo_sica'] ;  ?></td>

                            <td class="hidden-xs"><?php echo $this->lista[$i]['rif'] ?></td>
                            <td><?php echo $this->lista[$i]['razon_social'] ?>
                            <center>  
<table id="tabla<?php echo $i+1 ?>" hidden='hidden'  class="table table-list table-interna">
  <?php for ($x=0; $x < count($this->lista[$i]['resultado']); $x++): ?><tr>
  <td><?php echo $this->lista[$i]['resultado'][$x]['rif'] ?></td>
  <td><?php echo $this->lista[$i]['resultado'][$x]['nombres'] ?></td>
  <td><?php echo $this->lista[$i]['resultado'][$x]['nacionalidad'].$this->lista[$i]['resultado'][$x]['cedula'] ?>
    
  </td>
  

  <td>
     <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
     <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  </td>


    </tr>
<?php endfor; ?>
</table>
</center>

                              
                            </td>
                            <td><?php echo $this->lista[$i]['tipo'] ?></td>
                           <td><?php echo $this->lista[$i]['mun_socios'] ?></td>
                            <td><a href="<?php BASE_URL ?>regis_per?id=<?php echo $this->lista[$i]['id_emp']?>" class="btn btn-default" ><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></td>


                           </tr>


                          	<?php endfor; ?>
<!--end ciclo............................................................................................ -->
                        </tbody>
                </table>
            
              </div>

				<!-- footer -->

              <div class="panel-footer">
                <div class="row">
                  <div class="col col-xs-4">
                  </div>
                  <div class="col col-xs-8">
                    <ul class="pagination  pull-right">
                     
                     
                    </ul>
                   
                  </div>
                </div>
              </div>
          





	
</div>
		