
<div class="col-md-6 col-md-offset-3">


<div class="">
	<button class="md-trigger seleccion" data-modal="modal-1"> comprobante de registro</button>
</div>




<div class="">
	<button class="md-trigger seleccion" data-modal="modal-1">listado de inscripcion</button>
</div>




<div class="">
	<button class="md-trigger seleccion" data-modal="modal-1"> comprobante de registro</button>
</div>


</div>
		



<div class="md-modal md-effect-1" id="modal-1">
			<div class="md-content">
				<h3>comprobante de registro</h3>
				<div>
					<center><img class="img img-responsive" src="<?php echo BASE_URL ?>public/img/ojos.gif"></center>
					<p>Comprobante de registro del sistema de registro y planificación de productores del estado sucre </p>
<form class="form" role="form" method="get" action="<?php echo BASE_URL ?>pdf/comprobante_registro">
  <div class="form-group">
    <label  for="empresa">Empresa productora</label>
    <select class="form-control" id="id" name="id">
    	
    	<?php for ($i=0; $i < count($this->_empresas) ; $i++) { ?>
	    		<option value="<?php echo $this->_empresas[$i]['id_emp'] ?>"><?php echo $this->_empresas[$i]['razon_social'] ?></option>
	    	<?php } ?>
    </select>
  </div>
  
  
  <button type="submit" class="btn btn-default">Generar comprobante</button>
</form>

						<ul>
						<li><strong>CERRAR</strong> cliquee el boton Cerrar para canselar la generacion del comprobante.</li>
					</ul>
					<button class="md-close">CERRAR</button>
				</div>
			</div>
		</div>
		