

<div class="col-md-12">


<div class="buscar-agencias-div">
    

      <div class="input-group">
      <input type="text" class="form-control buscaragencia" id="agencia_name" name="agencia_name" placeholder="Buscar">

      <span class="input-group-btn">
        <button class="btn btn-danger" id="btn_buscar" type="button"><span class="glyphicon glyphicon-search"></span></button>
      </span>

          </div><!-- /input-group -->
<input type="hidden"  id="bn" name="bn" value="1" >

</div>

<div class="col-md-12" id="div_contenedor2">
		
	</div>
<div class="contenedor-img-agencia chicas-agencia" id="prevista">
		
	</div>

					
		</div>

	





