

<div class="col-md-10 col-md-offset-1">
		<div id="foto_grande " class="col-md-12 center-border margen_vista_nina"  style="position: static; margin-left: 15px;" >
		<a id="ver_perfil"><h1 class="dorado tex-col"><?php echo $this->datos['nombre_chicas'] ?>  <label class="popularidad"> &#9733; <?php echo round($this->valoracion['rating'],2) ?>Pts</label></h1></a> 
		</div>



	
	<div class="col-md-6">
		

		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

		  

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" role="listbox">
		    <div class="item active">
		      <img id="fotoG"  class="d-block img-fluid"  src="<?php echo BASE_URL?>/public/img/fotos/<?php echo $this->datos['fotos'][0]['nombre_foto'] ?>" >
		     
		    </div>

		   <?php for ($i=1; $i <count($this->datos['fotos']) ; $i++): ?>

		    <div class="item">
		      <img id="fotoG" class="d-block img-fluid"  src="<?php echo BASE_URL?>/public/img/fotos/<?php echo $this->datos['fotos'][$i]['nombre_foto'] ?>" >
		      
		    </div>

			<?php endfor; ?>

		  </div>

		  <!-- Controls -->
		  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>



	
	</div>

	<div class="col-md-6">
			<div class="row">
				<div class="col-md-5 xx">

					<?php
							date_default_timezone_set('America/Caracas'); 
	    					$fechac = $this->datos['fecha_nacimiento'];
	    					$hoy = date('Y/m/d');
	    					$fecha_actual = explode("/", $hoy);
							$nacimiento = explode("-", $fechac);

							if (($nacimiento[1] == $fecha_actual[1]) && ($nacimiento[2] > $fecha_actual[2])) {
							$fecha_actual[0]=($fecha_actual[0]-1); }

							if ($nacimiento[1] > $fecha_actual[1]) {
							$fecha_actual[0]=($fecha_actual[0]-1);}

							$edad=($fecha_actual[0]-$nacimiento[0]);
					?>
				
						<address>
						 <center> <h4 class="minititulo"> <b> Mis Caracteristicas </b></h4> </center>
						
						<b>Edad:</b> <?php echo $edad; ?> Años<br>
						<b>Estatura:</b> <?php echo $this->datos['estatura'] ?> Mts<br>
						<b>Peso:</b> <?php echo $this->datos['peso'] ?> Kgs<br>
						<b>Medidas:</b> <?php echo $this->datos['medidas'] ?><br>
						<b>Color de Ojos:</b> <?php echo $this->datos['color_ojos'] ?><br>
						<b>Color de Piel:</b> <?php echo $this->datos['color_piel'] ?><br>
						<b>Color de Cabello:</b> <?php echo $this->datos['color_cabello'] ?><br>
						
						<br>
						<center> <h4> <b> Mis Habilidades </b></h4> </center>
		
						<b>Destrezas:</b> <?php echo $this->datos['destrezas'] ?><br>
						<b>Especialidad:</b> <?php echo $this->datos['especialidad'] ?><br>
			
						</address>

					
				</div>
				<div class="col-md-5 xx">
				
						<address>
					<center> <h4 class="minititulo"> <b> Preview: </b></h4> </center>
					
							<p> <?php echo $this->datos['preview'] ?> </p>
					
						<br>
						<center> <h4 class="minititulo"> <b> Atiendo a: </b></h4> </center>
						
							<p> <?php echo $this->datos['publico'] ?> </p><br>
					
						
						<center> <h4 class="minititulo"> <b> Horario </b></h4> </center>
						
			
							<p><?php echo $this->datos['horario'] ?> </p>
						
						</address>
					</div>
			</div>

		</div>
	</div>
	<div class="col-md-10 col-md-offset-1">
		<div class="row">
			<div class="col-md-9 margen_vista_nina">
				<ul>



 
					<?php for ($i=0; $i <count($this->datos['fotos']) ; $i++): ?>


					<li data-target="#carousel-example-generic" data-slide-to="<?php echo $i; ?>" class="active">
						<div id="prevista" class="prviuw">
							 <img id="fotoG"  src="<?php echo BASE_URL?>/public/img/fotos/<?php echo $this->datos['fotos'][$i]['nombre_foto'] ?>" >
						</div>
					</li>

					<?php endfor; ?>


					 </ul>

			</div>
			<div class="col-md-3">

				<div id="contacto">
					<address>
					<strong>Contactame: </strong><br>
					<strong><b>Agencia:</b></strong>
					<abbr title="Agencia"></abbr> <?php echo $this->datos['nombre_agencia'] ?>
					<br>
					<span class="glyphicon glyphicon-earphone negro" id="negro"></span>
					<abbr title="Phone"></abbr> <?php echo $this->datos['tlf'] ?>
					<br><strong><b>Localidad:</b></strong>
					<abbr title="Localidad"></abbr> <?php echo $this->datos['localidad'] ?>
					<br>

					<?php if ($this->datos['instagram']!=""): ?>
					<a href="URL-Instagram" target="_blank"><img alt="<?php echo $this->datos['instagram'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/ig.png" title="sígueme en Instagram: <?php echo $this->datos['instagram'] ?>" width="32" /></a>
					<?php endif ?>

					<?php if ($this->datos['bbm']!=""): ?>
					<a href="bbm" target="_blank"><img alt="<?php echo $this->datos['bbm'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/bbm.png" title="Hablemos por BBM: <?php echo $this->datos['bbm'] ?>" width="32" /></a>
					<?php endif ?>

					<?php if ($this->datos['whatsapp']!=""): ?>
					<a href="whatsapp" target="_blank"><img alt="<?php echo $this->datos['whatsapp'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/whatsapp.png" title="Hablemos por WhatsApp: <?php echo $this->datos['whatsapp'] ?>" width="32" /></a>
					<?php endif ?>

					<?php if ($this->datos['twitter']!=""): ?>
					<a href="twitter" target="_blank"><img alt="<?php echo $this->datos['twitter'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/twitter.png" title="Sígueme en Twitter: <?php echo $this->datos['twitter'] ?>" width="32" /></a>
					<?php endif ?>

					<?php if ($this->datos['facebook']!=""): ?>
					<a href="facebook" target="_blank"><img alt="<?php echo $this->datos['facebook'] ?>" height="32" src="<?php echo BASE_URL?>/public/img/face.png" title="Sígueme en Facebook: <?php echo $this->datos['facebook'] ?>" width="32" /></a>
					<?php endif ?>
				</address>
				</div>
				

			</div>
	
			
					<div class="col-md-9 margen_vista_nina">
						
							  <div class="califica">
							  <form action="" method="post">
							  	 <label class="califica"><center><address><strong>¿Ya Conoces a <?php echo $this->datos['nombre_chicas'] ?>? Ella tiene un Rating de <?php echo round($this->valoracion['rating'],2)?>. dale una puntuación a tu experiencia con ella..</strong></address></center></label> <br>
								<pa class="clasificacion">
									<input id="radio1" class="votacion"  type="radio" name="estrellas" value="5">
									<label class="estrella" for="radio1">&#9733;</label>

									<input id="radio2" class="votacion" type="radio" name="estrellas" value="4">
									<label class="estrella" for="radio2">&#9733;</label>

									<input id="radio3" class="votacion" type="radio" name="estrellas" value="3">
									<label class="estrella" for="radio3">&#9733;</label>

									<input id="radio4" class="votacion" type="radio" name="estrellas" value="2">
									<label class="estrella" for="radio4">&#9733;</label>

									<input id="radio5" class="votacion" type="radio" name="estrellas" value="1">
									<label class="estrella" for="radio5">&#9733;</label>
									
									<input type="hidden" id="id_chica" value="<?php echo $this->datos['id_chicas'] ?>">
								</pa>
								</form>
								</div>
							
						</div>
				
				
				<div class="col-md-3">
					<?php if ($this->datos['email']!=""): ?>
						<div id="contacto">
							<address>
							<strong>E-Mail</strong><br>
							<span class='glyphicon glyphicon-envelope negro'></span>
							<a href="mailto:#"><?php echo $this->datos['email'] ?></a>
							</address>
						</div>
					<?php endif ?>
					

				</div>
		</div>
			


	</div>

		
		
		

