

<div id="titulo">actualizacion de datos de empresas productiva</div>
		
		
<div class="col-md-6 col-md-offset-3">
	
	
		<form id="agregar" action="">
	  <div class="form-group">
	    <label for="RIF">RIF</label>
	    <input type="text" disabled="disabled" class="form-control" id="rif" placeholder="RIF" value="<?php echo $this->datos['rif'] ?>">
	  </div>

	  <div class="form-group">
	    <label for="Razon_Social">Razon Social</label>
	    <input type="text" class="form-control" id="razon_social" placeholder="Razon Social" value="<?php echo $this->datos['razon_social'] ?>">
	  </div>

	   <div class="form-group">
	    <label for="codigo sica">codigo SICA</label>
	    <input type="text" class="form-control" id="codigo_sica" placeholder="codigo sica"
	    value="<?php echo $this->datos['codigo_sica'] ?>">
	  </div>

	  <div class="form-group">
	    <label for="Nro_de_Registro">Nro de Registro</label>
	    <input type="text" class="form-control" id="nro_de_registro" placeholder="Rro de Registro" value="<?php echo $this->datos['nro_de_registro'] ?>">
	  </div>

	  <div class="form-group">
	    <label for="Nombre del clap">Nombre de CLAP de la localidad</label>
	    <input type="text" class="form-control" id="clap" placeholder="Nombre del clap" value="<?php echo $this->datos['clap'] ?>">
	  </div>
	
	  <div class="form-group">
	    <label for="tipo">tipo de productor</label>
	    <select name="" id="tipo" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option value="Panadero" <?php echo $x = ($this->datos['tipo']=="Panadero") ? 'selected' : '' ; ?> >-Panadero-</option>
	    	<option value="Empanadero" <?php echo $x = ($this->datos['tipo']=="Empanadero") ? 'selected' : '' ; ?>>-Empanadero-</option>
	    	<option value="Pasteleria" <?php echo $x = ($this->datos['tipo']=="Pasteleria") ? 'selected' : '' ; ?>>-Pasteleria-</option>
	    	<option value="Dulceria" <?php echo $x = ($this->datos['tipo']=="Dulceria") ? 'selected' : '' ; ?>>-Dulceria-</option>
	    	<option value="Heladeria" <?php echo $x = ($this->datos['tipo']=="Heladeria") ? 'selected' : '' ; ?>>Heladeria-</option>
	    	<option value="Otros" <?php echo $x = ($this->datos['tipo']=="Otros") ? 'selected' : '' ; ?>>-Otros-</option>
	    </select>
	 </div>


	 <div class="form-group">
	    <label for="">Municipio</label>
	    <select name="" id="municipio" class="form-control">
	    	<option  value="">-seleccione-</option>
		<?php 
			for ($i=0; $i < count($this->_municipios) ; $i++) { ?>

<option  <?php echo $x = ($this->datos['municipio']==$this->_municipios[$i]['id_municipio']) ? 'selected' : '' ; ?>

value="<?php echo $this->_municipios[$i]["id_municipio"] ?>"><?php echo $this->_municipios[$i]["municipio"] ?></option>

		<?php 		
			}
		 ?>
	    </select>
	 </div>



	 <input type="hidden" id='parroquia_2' value="<?php echo $this->datos['parroquia'] ?>">
	 <div class="form-group">
	    <label for="Parroquia">Parroquia</label>
	    <select name="" id="parroquia" class="form-control">
	    	<option value="">-Seleccione-</option>
	    	
	    </select>
	 </div>

	  <div class="form-group">
	    <label for="Direccion">Direccion</label>
	    <input type="text" class="form-control" id="direccion" placeholder="Direccion" value="<?php echo $this->datos['direccion'] ?>">
	  </div>

	  <div class="form-group">
	    <label for=""> ¿posee certificados del inces?</label>
	    <select name="" id="poseec" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option  <?php echo $x = ($this->datos['poseec']=='SI') ? 'selected' : '' ; ?> value="SI">-SI-</option>
	    	<option  <?php echo $x = ($this->datos['poseec']=='NO') ? 'selected' : '' ; ?> value="NO">-NO-</option>
	    </select>
	 </div>
	 	<div class="form-group">
	    <label for="">¿posee permiso sanitario?</label>
	    <select name="" id="poseep" class="form-control">
	    	<option value="">-seleccione-</option>
	    	<option <?php echo $x = ($this->datos['poseep']=='SI') ? 'selected' : '' ; ?>  value="SI">-SI-</option>
	    	<option <?php echo $x = ($this->datos['poseep']=='NO') ? 'selected' : '' ; ?>  value="NO">-NO-</option>
	    </select>
	 </div> 	

	
	
	  <button type="button" id="actualizar" class="btn btn-default">ACTUALIZAR</button>
	   <button type="button" id="inicio" class="btn btn-default">Inicio</button>
	</form>

	</div>
		
