


<div id="titulo">Registro de Empresas Productivas</div>
		
		
<div class="col-md-6 col-md-offset-3">
	
	
		<form id="agregar" action="">
	  <div class="form-group">
	    <label for="RIF">RIF</label>
	    <input type="text" class="form-control" id="rif" placeholder="RIF">
	  </div>

	  <div class="form-group">
	    <label for="Razon_Social">Razon Social</label>
	    <input type="text" class="form-control" id="razon_social" placeholder="Razon Social">
	  </div>

	   <div class="form-group">
	    <label for="codigo sica">Codigo SICA</label>
	    <input type="text" class="form-control" id="codigo_sica" placeholder="codigo sica">
	  </div>

	  <div class="form-group">
	    <label for="Nro_de_Registro">Nro de Registro</label>
	    <input type="text" class="form-control" id="nro_de_registro" placeholder="Rro de Registro">
	  </div>

	  <div class="form-group">
	    <label for="Nombre del clap">Nombre de CLAP de la localidad</label>
	    <input type="text" class="form-control" id="clap" placeholder="Nombre del clap">
	  </div>

	 <div class="form-group">
            <label for="tipo">Tipo de Productor</label>
           <select class="form-control" id="tipo" name="codigo">
            <option value="">--Seleccione--</option>
            <?php for($i=0;$i<count($this->tipo);$i++):?>
              <option value="<?php echo $this->tipo[$i]['nombre_tipo'] ?>">
              <?php echo $this->tipo[$i]['nombre_tipo']; ?>                
              </option>
              
              <?php  endfor; ?>
            </select>
          </div>


	 <div class="form-group">
	    <label for="">Municipio</label>
	    <select name="" id="municipio" class="form-control">
	    	<option  value="">--Seleccione--</option>
		<?php 
			for ($i=0; $i < count($this->_municipios) ; $i++) { ?>

				<option value="<?php echo $this->_municipios[$i]["id_municipio"] ?>"><?php echo $this->_municipios[$i]["municipio"] ?></option>

		<?php 		
			}
		 ?>
	    </select>
	 </div>

	 <div class="form-group">
	    <label for="Parroquia">Parroquia</label>
	    <select name="" id="parroquia" class="form-control">
	    	<option value="">--Seleccione--</option>
	    	
	    </select>
	 </div>

	  <div class="form-group">
	    <label for="Direccion">Dirección</label>
	    <input type="text" class="form-control" id="direccion" placeholder="Direccion">
	  </div>

	  <div class="form-group">
	    <label for=""> ¿Posee certificados del Inces?</label>
	    <select name="" id="poseec" class="form-control">
	    	<option value="">--Seleccione--</option>
	    	<option value="SI">SI</option>
	    	<option value="NO">NO</option>
	    </select>
	 </div>
	 	<div class="form-group">
	    <label for="">¿Posee permiso sanitario?</label>
	    <select name="" id="poseep" class="form-control">
	    	<option value="">--Seleccione--</option>
	    	<option value="SI">SI</option>
	    	<option value="NO">NO</option>
	    </select>
	 </div> 	

	
	<center>
	  <button type="button" id="guardar" class="btn btn-default">Guardar</button>
	  <button type="button" id="inicio" class="btn btn-default">Inicio</button>
	</center>
	</form>

	</div>
		
